config/routes.rb
Rails.application.routes.draw do
  resources :webfiles

  root 'webfiles#index'

  get 'export', to: 'webfiles#export', as: :phone_export

end

app/models/webfile.rb
class Webfile < ActiveRecord::Base


	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv.add_row column_names
	    all.each do |webfile|
	      values = webfile.attributes.values
	      csv.add_row values
	    end
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/webfiles_controller.rb
class WebfilesController < ApplicationController
  before_action :set_webfile, only: [:show, :edit, :update, :destroy]

  # GET /webfiles
  # GET /webfiles.json
  def index
    @webfiles = Webfile.all
  end

  # GET /webfiles/1
  # GET /webfiles/1.json
  def show
  end

  # GET /webfiles/new
  def new
    @webfile = Webfile.new
  end

  # GET /webfiles/1/edit
  def edit
  end

  # POST /webfiles
  # POST /webfiles.json
  def create
    @webfile = Webfile.new(webfile_params)

    respond_to do |format|
      if @webfile.save
        format.html { redirect_to @webfile, notice: 'Webfile was successfully created.' }
        format.json { render :show, status: :created, location: @webfile }
      else
        format.html { render :new }
        format.json { render json: @webfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webfiles/1
  # PATCH/PUT /webfiles/1.json
  def update
    respond_to do |format|
      if @webfile.update(webfile_params)
        format.html { redirect_to @webfile, notice: 'Webfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @webfile }
      else
        format.html { render :edit }
        format.json { render json: @webfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webfiles/1
  # DELETE /webfiles/1.json
  def destroy
    @webfile.destroy
    respond_to do |format|
      format.html { redirect_to webfiles_url, notice: 'Webfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def export
    @data = Webfile.order(:created_at)
    respond_to do |format|
      format.html { redirect_to root_url }
      format.csv { send_data @data.to_csv }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webfile
      @webfile = Webfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webfile_params
      params.require(:webfile).permit(:name, :phone_number, :category, :address, :area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webfiles_helper.rb
module WebfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webscrapper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/webfiles/_form.html.erb
<%= form_for(@webfile) do |f| %>
  <% if @webfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@webfile.errors.count, "error") %> prohibited this webfile from being saved:</h2>

      <ul>
      <% @webfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webfiles/edit.html.erb
<h1>Editing Webfile</h1>

<%= render 'form' %>

<%= link_to 'Show', @webfile %> |
<%= link_to 'Back', webfiles_path %>

app/views/webfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Webfiles</h1>

<table>
  <thead>
    <tr>
      <th>Categories</th>
      <th>Name</th>
      <th>Phone number</th>
      <th>Address</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webfiles.each do |webfile| %>
      <tr>
        <td><%= webfile.category %></td>
        <td><%= webfile.name %></td>
        <td><%= webfile.phone_number %></td>
        <td><%= webfile.address %></td>
        <td><%= webfile.area %></td>
        <!-- <td><%= link_to 'Show', webfile %></td>
        <td><%= link_to 'Edit', edit_webfile_path(webfile) %></td>
        <td><%= link_to 'Destroy', webfile, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody><hr>
</table>

<br>

<%= link_to 'New Webfile', new_webfile_path %>
<%= link_to "Export Data", phone_export_path(format: "csv") %>

app/views/webfiles/new.html.erb
<h1>New Webfile</h1>

<%= render 'form' %>

<%= link_to 'Back', webfiles_path %>

app/views/webfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @webfile.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @webfile.phone_number %>
</p>

<%= link_to 'Edit', edit_webfile_path(@webfile) %> |
<%= link_to 'Back', webfiles_path %>